[package]
name = "iced_wayland_topbar"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.12"
# Iced (UI)
iced = { version = "0.14.0", features = ["canvas", "svg"] }
iced_layershell = "0.15.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
